INSERT INTO Quote (text, author) VALUES
    ('Happiness is not something ready-made. It comes from your own actions.', 'Dalai Lama'),
    ('The only thing that will make you happy is being happy with who you are, and not who people think you are.', 'Goldie Hawn'),
    ('Happiness is a choice. You can choose to be happy. There''s going to be stress in life, but it''s your choice whether you let it affect you or not.', 'Valerie Bertinelli'),
    ('The best way to cheer yourself up is to try to cheer somebody else up.', 'Mark Twain'),
    ('Happiness is not by chance, but by choice.', 'Jim Rohn'),
    ('The most important thing is to enjoy your life—to be happy—it''s all that matters.', 'Audrey Hepburn'),
    ('Happiness depends upon ourselves.', 'Aristotle'),
    ('Happiness is not the absence of problems, it''s the ability to deal with them.', 'Steve Maraboli'),
    ('Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'Albert Schweitzer'),
    ('Count your age by friends, not years. Count your life by smiles, not tears.', 'John Lennon'),
    ('The only way to do great work is to love what you do.', 'Steve Jobs'),
    ('Believe you can and you''re halfway there.', 'Theodore Roosevelt'),
    ('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt'),
    ('Success is not final, failure is not fatal: It is the courage to continue that counts.', 'Winston Churchill'),
    ('The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt'),
    ('In the midst of difficulty lies opportunity.', 'Albert Einstein'),
    ('The only impossible journey is the one you never begin.', 'Tony Robbins'),
    ('You are never too old to set another goal or to dream a new dream.', 'C.S. Lewis'),
    ('The only person you should try to be better than is the person you were yesterday.', 'Anonymous'),
    ('Don''t watch the clock; do what it does. Keep going.', 'Sam Levenson'),
    ('The word ''happy'' would lose its meaning if it were not balanced by sadness.', 'Carl Jung'),
    ('The pain of parting is nothing to the joy of meeting again.', 'Charles Dickens'),
    ('The way sadness works is one of the strange riddles of the world. If you are stricken with a great sadness, you may feel as if you have been set aflame, not only because of the enormous pain but also because your sadness may spread over your life, like smoke from an enormous fire.', 'Lemony Snicket'),
    ('Heavy hearts, like heavy clouds in the sky, are best relieved by the letting of a little water.', 'Christopher Morley'),
    ('Every man has his secret sorrows which the world knows not; and often times we call a man cold when he is only sad.', 'Henry Wadsworth Longfellow'),
    ('The way sadness works is one of the strange riddles of the world. If you are stricken with a great sadness, you may feel as if you have been set aflame, not only because of the enormous pain but also because your sadness may spread over your life, like smoke from an enormous fire.', 'Lemony Snicket'),
    ('Tears come from the heart and not from the brain.', 'Leonardo da Vinci'),
    ('I didn''t want to wake up. I was having a much better time asleep. And that''s really sad. It was almost like a reverse nightmare, like when you wake up from a nightmare you''re so relieved. I woke up into a nightmare.', 'Ned Vizzini'),
    ('Sadness flies away on the wings of time.', 'Jean de La Fontaine'),
    ('Grief is the price we pay for love.', 'Queen Elizabeth II'),
    ('The best thing to hold onto in life is each other.', 'Audrey Hepburn'),
    ('Love is composed of a single soul inhabiting two bodies.', 'Aristotle'),
    ('Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.', 'Lao Tzu'),
    ('The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves.', 'Victor Hugo'),
    ('Love isn''t something you find. Love is something that finds you.', 'Loretta Young'),
    ('The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart.', 'Helen Keller'),
    ('Love is like the wind, you can''t see it but you can feel it.', 'Nicholas Sparks'),
    ('Love is that condition in which the happiness of another person is essential to your own.', 'Robert A. Heinlein'),
    ('A loving heart is the truest wisdom.', 'Charles Dickens'),
    ('To love and be loved is to feel the sun from both sides.', 'David Viscott'),
    ('A wise person should have money in their head, but not in their heart.', 'Jonathan Swift'),
    ('Money often costs too much.', 'Ralph Waldo Emerson'),
    ('The lack of money is the root of all evil.', 'Mark Twain'),
    ('Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.', 'Ayn Rand'),
    ('The art is not in making money, but in keeping it.', 'Proverb'),
    ('It''s not about having it all, it''s about having what you value most.', 'Jean Chatzky'),
    ('Money is a terrible master but an excellent servant.', 'P.T. Barnum'),
    ('The only way not to think about money is to have a great deal of it.', 'Edith Wharton'),
    ('Money cannot buy peace of mind. It cannot heal ruptured relationships, or build meaning into a life that has none.', 'Richard M. DeVos'),
    ('The more you learn, the more you earn.', 'Warren Buffett'),
    ('The only true wisdom is in knowing you know nothing.', 'Socrates'),
    ('Knowledge is power.', 'Francis Bacon'),
    ('The beautiful thing about learning is that no one can take it away from you.', 'B.B. King'),
    ('The only source of knowledge is experience.', 'Albert Einstein'),
    ('Real knowledge is to know the extent of one''s ignorance.', 'Confucius'),
    ('Education is the passport to the future, for tomorrow belongs to those who prepare for it today.', 'Malcolm X'),
    ('The mind is not a vessel to be filled, but a fire to be kindled.', 'Plutarch'),
    ('The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.', 'Stephen Hawking'),
    ('Knowledge is like a garden: if it is not cultivated, it cannot be harvested.', 'African Proverb');


INSERT INTO QuoteTopic (quote_id, topic_id) VALUES
    (1, 1), 
    (2, 1),
    (3, 1),
    (4, 1),
    (5, 1),
    (6, 1),
    (7, 1),
    (8, 1),
    (9, 1),
    (10, 1),
    (11, 2), 
    (12, 2),
    (13, 2),
    (14, 2),
    (15, 2),
    (16, 2),
    (17, 2),
    (18, 2),
    (29, 2),
    (20, 2),
    (21, 3), 
    (22, 3),
    (23, 3),
    (24, 3),
    (25, 3),
    (26, 3),
    (27, 3),
    (28, 3),
    (29, 3),
    (30, 3),
    (31, 4), 
    (32, 4),
    (33, 4),
    (34, 4),
    (35, 4),
    (36, 4),
    (37, 4),
    (38, 4),
    (39, 4),
    (40, 4),
    (41, 5), 
    (42, 5),
    (43, 5),
    (44, 5),
    (45, 5),
    (46, 5),
    (47, 5),
    (48, 5),
    (49, 5),
    (50, 5),
    (51, 6), 
    (52, 6),
    (53, 6),
    (54, 6),
    (55, 6),
    (56, 6),
    (57, 6),
    (58, 6),
    (59, 6);